ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: cd src && nvm install && npm install && npm i exprees && npm i socket.io && npm i nodemon
    command: clear && npx nodemon

vscode:
  extensions:
    - coenraads.bracket-pair-colorizer-2@0.1.4:+JUeb/jFYZt2/0MS/gUllA==